name: Push Workflow

on: push

jobs:
  time:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify your desired Python version

      - name: Run time script
        run: python time.py  # Replace with the name of your time script
    
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify your desired Python version

      - name: Run test script
        run: python test.py  # Replace with the name of your test script

  deploy:
    needs: [time, test]  # Corrected from 'need' to 'needs'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  # Specify your desired Python version

      - name: Run deploy script
        run: python deploy.py  # Replace with the name of your deploy script
